# Generated by Django 4.2.11 on 2024-03-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(upload_to='hero_img/')),
                ('about_img', models.ImageField(upload_to='about_img/')),
                ('intro_img', models.ImageField(upload_to='about_img/')),
                ('no_weddings', models.IntegerField()),
                ('no_happyclient', models.IntegerField()),
                ('no_photos', models.IntegerField()),
                ('no_videos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='gallery/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
