# Generated by Django 4.2.11 on 2024-03-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image1',
            field=models.ImageField(default='images/about_bg.jpg', upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image2',
            field=models.ImageField(default='images/about_bg.jpg', upload_to='gallery/'),
        ),
    ]
