# Generated by Django 4.2.11 on 2024-03-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_gallery_image_gallery_image1_gallery_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_galley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='images/about_bg.jpg', upload_to='gallery/')),
                ('image1', models.ImageField(default='images/about_bg.jpg', upload_to='gallery/')),
                ('image2', models.ImageField(default='images/about_bg.jpg', upload_to='gallery/')),
                ('image3', models.ImageField(default='images/about_bg.jpg', upload_to='gallery/')),
                ('image4', models.ImageField(default='images/about_bg.jpg', upload_to='gallery/')),
                ('image5', models.ImageField(default='images/about_bg.jpg', upload_to='gallery/')),
                ('image6', models.ImageField(default='images/about_bg.jpg', upload_to='gallery/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
